/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeJava */

#ifndef _Included_NativeJava
#define _Included_NativeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeJava
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeJava_square
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
